<?php declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Stephen\LandingPages\ViewModel\HeroProduct;

/* @var $block Template */
/* @var $heroProduct HeroProduct */
/* @var $escaper Escaper */
$heroProduct = $block->getData('hero_product');
$product = $heroProduct->getProduct(2);
$currencySymbol = $heroProduct->getCurrencySymbol();
$taxRate = $heroProduct->getTaxRate($product);
$image = $heroProduct->getProductImage($product, 'product_small_image');
?>

<h2>Product</h2>
<a href="<?= $escaper->escapeUrl($product->getProductURL()) ?>">
    <div>
        <p><strong><?= $escaper->escapeHtml(__('Name:')) ?> </strong><?= $escaper->escapeHtml($product->getData('name')) ?></p>
        <p><strong><?= $escaper->escapeHtml(__('SKU:')) ?> </strong><?= $escaper->escapeHtml($product->getData('sku')) ?></p>
        <p>
            <strong><?= $escaper->escapeHtml(__('Price:')) ?> </strong><?= $escaper->escapeHtml($currencySymbol) . $escaper->escapeHtml($product->getFinalPrice()) ?>
            <strong> <?= $escaper->escapeHtml(__('Tax:')) ?> </strong> <?= $escaper->escapeHtml($taxRate) ?>%
        </p>
        <p><strong><?= $escaper->escapeHtml(__('URL:')) ?> </strong><?= $escaper->escapeHtml($product->getProductURL()); ?></p>
        <img alt="<?= $escaper->escapeHtmlAttr($product->getData('name')) ?>" src="<?= $escaper->escapeUrl($image) ?>"/>
    </div>
</a>
